### PR TITLE
Inline typedefs from deprecated/removed C++98 function adapters.

### PR DESCRIPTION
**Pull request by DanielaE**
Signed-off-by: Daniela Engert <dani@ngrt.de>

### CODE REVIEW

**Comment by pavelkryukov** [comment]
@danieljames Could you please take a look here as well?

**Comment by pdimov** [comment]
`test_bimap_unordered` fails for me on all versions of MSVC, but I have no idea why. Oh well.

PS You were summoning the wrong demon, @pavelkryukov. :-)

**Comment by pavelkryukov** [comment]
@pdimov But the right one was summoned :-)

**Comment by pavelkryukov** [comment]
@pdimov Peter, there is one open PR regarding the same issue: https://github.com/boostorg/gil/pull/16

**Comment by pdimov** [comment]
GIL is being actively maintained, so I'd rather not intervene there.

**Pull request merged**
